---
title: "Avocado Prices Project"
author: "Rohan Janakiraman"
date: "11/26/2019"
output: html_document
---

```{r setup, include=FALSE}
```

```{r}
install.packages("GauPro")
```


```{r}
prices <- Avocado_Prices_Data[c(3)]
typeof(prices)
#hist(prices)
```

```{r}
library("readxl")
# xlsx files
my_data <- read_excel(file.choose())
```

```{r}
install.packages("e1071")
library(e1071)
```


```{r}
library(dplyr)
#Plots Histograms of Average Avocado Price for Each Year in Dataset and Basic Statistics for Each Year 
years <- c(2015, 2016, 2017, 2018)
colors <- c("red", "yellow", "568203", "#6ba304")
index <- 1
for(time in years){
  avocado_data = filter(my_data, my_data$year == years[index])
  string_year = toString(years[index])
  title_text = paste("Distribution of Avocado Prices", string_year, sep=", ")
  with(avocado_data, hist(AveragePrice, main= title_text,
  xlab="Average Avocado Price", breaks=120, col = colors[index]))
  
  mean = with(avocado_data, mean(AveragePrice))
  print(paste(string_year, "mean:", sep=" "))
  print(mean)
  
  variance = with(avocado_data, var(AveragePrice))
  print(paste(string_year, "variance: ", sep=" "))
  print(variance)
  
  range = with(avocado_data, range(AveragePrice))
  print(paste(string_year, "range: ", sep=" "))
  print(range)
  
  quantiles = with(avocado_data, quantile(AveragePrice, c(0.025, 0.975)))
  print(paste(string_year, "2.5th percentile: ", sep=" "))
  print(quantiles[1])
  print(paste(string_year, "97.5th percentile: ", sep=" "))
  print(quantiles[2])
  
  index = index + 1
}

#Plots Histogram of Average Avocado Price for All Years in Dataset 
#This is Figure 1 in Final Report 
with(my_data, hist(AveragePrice, main = "Distribution of Avocado Prices", 
                   xlab="Average Avocado Price", breaks=120, col = "purple"))
```

```{r}
#Plots Price of Organic Avocados in West Texas and New Mexico region over period
library(tidyverse)
modified_data_1 = filter(my_data, region == c("WestTexNewMexico"), type == "organic", year == c(2015, 2016, 2017, 2018))
 ggplot(data = modified_data_1, mapping = aes(x = Date, y = AveragePrice)) + 
   geom_point(mapping = aes(color = "red")) +
  geom_line(mapping = aes(color = "red")) + 
  geom_smooth() +
  ggtitle("Price of Organic Avocadoes in West Texas and New Mexico")

```

```{r}
#Time Trend in Average Price for Entire Dataset 
#This is Figure 2 in Final Report
ggplot(data = my_data, mapping = aes(x = Date, y = AveragePrice)) + geom_point(mapping = aes(color = year)) + geom_smooth(color = "red") 
```



```{r}
#Plots Price of Organic Avocados in California region over period
library(tidyverse)
modified_data = filter(my_data, region == c("California"), type == "organic", year == c(2015, 2016, 2017, 2018))
 ggplot(data = modified_data, mapping = aes(x = Date, y = AveragePrice)) + 
   geom_point(mapping = aes(color = "red")) +
  geom_line(mapping = aes(color = "red")) + 
  ggtitle("Organic Avocadoes in California")
```

```{r}
#Tabulates Number of Rows in Dataset and List Unique Regions
nrow(my_data)
unique(my_data$region)
```


```{r}
#Box Whisker Plot of Price Range by Type for San Francisco, San Diego, New York, Detroit, Dallas Ft Worth, Boston
#This is Figure 3 
library(tidyverse)
modified_data = filter(my_data, region == c("Boston", "DallasFtWorth" ,"Detroit", "NewYork", "SanDiego", "SanFrancisco", "NewYork"))
regional_plot = ggplot(data = modified_data, mapping = aes(x = region, y = AveragePrice)) + geom_boxplot(color = "#6ba304", fill = "#568203") + facet_wrap(~ type) + coord_flip()
print(regional_plot + ggtitle("Avocado Price Range By Region and Type"))
```

```{r}
#Tabulating Differences between Conventional and Organic Data -- For use later in paper

organic_data = filter(my_data, type == "organic")
conventional_data = filter(my_data, type == "conventional")
mean(organic_data$AveragePrice)
mean(conventional_data$AveragePrice)
var(organic_data$AveragePrice)
var(conventional_data$AveragePrice)
nrow(organic_data)
nrow(conventional_data)
quantile(organic_data$AveragePrice, 0.75)
quantile(organic_data$AveragePrice, 0.25)
quantile(conventional_data$AveragePrice, 0.75)
quantile(conventional_data$AveragePrice, 0.25)
```
