---
title: "gaupro"
author: "Zack Light"
date: "11/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(GauPro)
```

# source
https://github.com/CollinErickson/GauPro

```{r}
n <- 12
x <- matrix(seq(0,1,length.out = n), ncol=1)
y <- sin(2*pi*x) + rnorm(n,0,1e-1)
gp <- GauPro::GauPro(X=x, Z=y)
curve(gp$pred(x));points(x,y)
curve(gp$pred(x)+2*gp$pred(x,T)$se,col=2,add=T);curve(gp$pred(x)-2*gp$pred(x,T)$se,col=2,add=T)
```

```{r}
curve(sapply(x, gp$deviance_theta_log),-10,10, n = 300) # deviance profile
```

```{r}
n <- 12
x <- matrix(seq(0,1,length.out = n), ncol=1)
y <- (2*x) %%1
gp <- GauPro::GauPro(X=x, Z=y)
curve(gp$pred(x));points(x,y)
curve(gp$pred(x)+2*gp$pred(x,T)$se,col=2,add=T);curve(gp$pred(x)-2*gp$pred(x,T)$se,col=2,add=T)
```

```{r}
curve(sapply(x, gp$deviance_theta_log),-10,10, n = 300) # deviance profile
```
Trying different kernels
```{r}
# GauPro_kernel$new(0), GauPro_kernel_beta$new(0),

kernels <- c( Exponential$new(0), Matern32$new(0), Matern52$new(0),  Gaussian$new(0), Periodic$new(p=1, alpha=1), RatQuad$new(beta=0, alpha=0))

for (kernel in kernels) {
  gpk <- GauPro_kernel_model$new(matrix(x, ncol=1), y, kernel=kernel, parallel=TRUE)
  plot(gpk)
} 

```

